modLoader="javafml"
loaderVersion="[2,)" # akzeptiert alle NeoForge 2.x
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
